on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

env:
  PROJECT: actions-adventures
  LINUX_TARGET: x86_64-unknown-linux-gnu
  MACOS_TARGET: x86_64-apple-darwin

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: $LINUX_TARGET
          - os: macos-latest
            target: $MACOS_TARGET
    name: Build artifact
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and package
        run: |
          tar czvf $PROJECT-${{ matrix.target }}.tar.gz README.md
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: $PROJECT-${{matrix.target}}
          path: $PROJECT-${{matrix.target}}.tar.gz
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
        run: echo '::set-env name=UPLOAD_URL::${{ steps.create_release.outputs.upload_url }}'
      - name: Upload linux
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./$PROJECT-${{ matrix.target }}.tar.gz
          asset_name: $PROJECT-${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload macos
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./$PROJECT-${{ matrix.target }}.tar.gz
          asset_name: $PROJECT-${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip
